import React, { useState } from 'react';
import { Accordion, AccordionItem, Tag } from '@carbon/react';
import { Information } from '@carbon/icons-react';

const AnswerContext = ({ sources, confidence }) => {
  if (!sources || sources.length === 0) return null;

  const topics = new Set();
  sources.forEach((source) => {
    if (source.section) topics.add(source.section);
    const fn = source.filename || '';
    if (fn.includes('Security')) topics.add('Security');
    if (fn.includes('AI')) topics.add('AI');
    if (fn.includes('Performance')) topics.add('Performance');
    if (fn.includes('Resilience')) topics.add('Resilience');
  });
  const topicsList = Array.from(topics).slice(0, 5);

  const confidenceNote = {
    high: 'high confidence based on strong source matches',
    medium: 'medium confidence with good source relevance',
    low: 'lower confidence — consider refining your query',
  }[confidence];

  return (
    <div style={{ marginTop: '1rem' }}>
      <Accordion>
        <AccordionItem
          title={
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <Information size={16} />
              <span className="cds--type-body-short-01">Why this answer?</span>
            </div>
          }
        >
          <p className="cds--type-body-short-01" style={{ color: 'var(--cds-text-secondary)', marginBottom: '0.75rem' }}>
            This answer was generated by analysing {sources.length} relevant{' '}
            {sources.length === 1 ? 'source' : 'sources'} from the LinuxONE documentation.
          </p>

          {topicsList.length > 0 && (
            <div style={{ marginBottom: '0.5rem' }}>
              <p className="cds--type-helper-text-01" style={{ fontWeight: 600, marginBottom: '0.375rem' }}>
                Topics covered:
              </p>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.375rem' }}>
                {topicsList.map((topic, i) => (
                  <Tag key={i} type="gray" size="sm">{topic}</Tag>
                ))}
              </div>
            </div>
          )}

          {confidence && confidenceNote && (
            <p className="cds--type-helper-text-01" style={{ color: 'var(--cds-text-secondary)', marginTop: '0.5rem' }}>
              <strong>Confidence:</strong> The answer has {confidenceNote}.
            </p>
          )}
        </AccordionItem>
      </Accordion>
    </div>
  );
};

export default AnswerContext;

// Made with Bob
